

# Global variables


stages:
  - build
  - push 
  - tag
  - deploy

# Blanket rules when this pipeline should run, regardless of job-specific conditions
workflow:
  rules:
    # Run for pull requests (creation/push)
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    # Run for pushes to master (direct pushs, merges)
    - if: $CI_COMMIT_BRANCH == "master"
    # Run when manually triggered by the gitlab UI
    - if: $CI_PIPELINE_SOURCE == "web"